# Generated by Django 5.1.2 on 2024-11-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0218_system_settings_enforce_verified_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jira_instance',
            name='default_issue_type',
            field=models.CharField(choices=[('Task', 'Task'), ('Story', 'Story'), ('Epic', 'Epic'), ('Spike', 'Spike'), ('Bug', 'Bug'), ('Security', 'Security'), ('Vulnerability', 'Vulnerability')], default='Bug', help_text='You can define extra issue types in settings.py', max_length=255),
        ),
    ]
